#+TITLE:   Private module for doom emacs
#+DATE:    January 9, 2019
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages
* Table of Contents :TOC_3:noexport:
- [[Description][Description]]
  - [[Module Flags][Module Flags]]
  - [[Plugins][Plugins]]
  - [[Hacks][Hacks]]
- [[Prerequisites][Prerequisites]]
- [[Features][Features]]
- [[Configuration][Configuration]]
- [[Troubleshooting][Troubleshooting]]

* Description
This is a private module for my personal. The config files mainly from
https://github.com/xhcoding/doom-private , Add I changed some personal config
for me, and I maybe add some functions. Thanks [[https://xhcoding.github.io/][xhcoding]] again.
+ autocomplete
+ TODO : blog manager
+ TODO : translate with youdao
** Module Flags
This module provides no flags.
** Plugins
[[https://github.com/auto-complete/auto-complete][auto-complete]]
** Hacks
{A list of internal modifications to included packages}
* Prerequisites
This module prereqisites with :
+ [[https://github.com/hlissner/doom-emacs][doom emacs]] : a emacs distribution like Spacemacs
+ [[https://github.com/MaskRay/ccls/wiki/Build][ccls]] : a completion server like YouCompleteMe
* Features
An in-depth list of features, how to use them, and their dependencies.
* Configuration
#+BEGIN_SRC bash
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d -b develop
git clone https://github.com/Jerling/doom.git ~/.config/doom
cd ~/.emacs.d && make install
#+END_SRC
* Troubleshooting
Common issues and their solution, or places to look for help.
