#+TITLE:   Private module for doom emacs
#+DATE:    January 9, 2019
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages
* Table of Contents :TOC_3:noexport:
- [[Description][Description]]
  - [[Module Flags][Module Flags]]
  - [[Plugins][Plugins]]
  - [[Hacks][Hacks]]
- [[Prerequisites][Prerequisites]]
- [[Features][Features]]
- [[Configuration][Configuration]]
  - [[Recommend][Recommend]]
- [[Troubleshooting][Troubleshooting]]

* Description
This is a private module for my personal. The config files mainly from
https://github.com/xhcoding/doom-private , Add I changed some personal config
for me, and I maybe add some functions. Thanks [[https://xhcoding.github.io/][xhcoding]] again.
+ Translate with youdao
+ Blog manager : [[https://github.com/masasam/emacs-easy-hugo][easy-hugo]] for manage org files , [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] export org to markdown .
** Module Flags
This module provides no flags.
** Plugins
This config will auto install packages; 
** Hacks
{A list of internal modifications to included packages}
* Prerequisites
This module prereqisites with :
+ [[https://github.com/hlissner/doom-emacs][doom emacs]] : a emacs distribution like Spacemacs
+ [[https://github.com/MaskRay/ccls/wiki/Build][ccls]] : a completion server like YouCompleteMe
* Features
An in-depth list of features, how to use them, and their dependencies.
* Configuration
#+BEGIN_SRC bash
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d -b develop
git clone https://github.com/Jerling/doom.git ~/.config/doom
cd ~/.emacs.d && make install
#+END_SRC
** Recommend
Maybe want to remap somekey on system, like CapsLock remap to Left_Ctrl and so
on. Install [[https://github.com/mooz/xkeysnail][xkeysnail]] , and then run the command as follow:
#+BEGIN_SRC bash 
nohup sudo xkeysnail ~/.config/doom/tools/config.py >> /dev/null &
# or write a script with autostart when longin
echo passwd | sudo -S xkeysnail ~/.config/doom/tools/config.py &
#+END_SRC

* Troubleshooting
- for TAGS not find : Maybe need reboot or install rtags reboot for goto definition work well;
